#!/bin/bash
#
# mem-cpu-stats - Print a summary of memory and CPU usage at a regular interval.
# Author: Jason Cox
# Repo: https://github.com/jasonccox/mem-cpu-stats

MEM_WIDTH=3
CPU_WIDTH=4
INTERVAL=5
NUM_ITERS=
COLORS=

usage() {
    echo \
"USAGE: mem-cpu-stats [OPTIONS]

Available OPTIONS:
    -c | --colors STYLE        Colorize the bars in STYLE. Currently the only
                               supported style is tmux. Default none.
    -i | --interval INTERVAL   Print output every INTERVAL seconds. INTERVAL
                               must be an integer greater than 0. Default 5.
    -m | --mem-width WIDTH     Display the memory usage number with at least
                               WIDTH characters. Default 3.
    -n | --num-iters NUM       Exit after NUM intervals. An empty value is
                               interpreted as infinity. Default infinity.
    -p | --cpu-width WIDTH     Display the CPU usage number with at least WIDTH
                               characters. Default 4.
"
}

main() {
    OS="$(get_os)"
    if [ "$OS" = other ]; then
        echo "unsupported OS"
        exit 1
    fi

    parse_options $@

    local n=0
    while [ -z "$NUM_ITERS" ] || [ "$n" -lt "$NUM_ITERS" ]; do
        local stats="$(get_stats)"

        local total_mem="$(echo "$stats" | awk '{print $1}')"
        local used_mem="$(echo "$stats" | awk '{print $2}')"
        local cpu_percent="$(echo "$stats" | awk '{print $3}')"

        local used_mem_gb="$(echo "scale=1; $used_mem / 1024" | bc)"
        local mem_percent="$(echo "scale=1; $used_mem * 100 / $total_mem" | bc)"

        local used_mem_fmt="$(printf '%*.1f' $MEM_WIDTH $used_mem_gb)"
        local cpu_percent_fmt="$(printf '%*.1f' $CPU_WIDTH $cpu_percent)"

        local mem_out="${used_mem_fmt}G $(bar $mem_percent)"
        local cpu_out="${cpu_percent_fmt}% $(bar $cpu_percent)"

        echo "$mem_out  $cpu_out"

        n="$((n + 1))"
        sleep $(($INTERVAL - 1)) # subtract 1 because top takes 1 second
    done
}

parse_options() {
    while [ "$1" != "" ]; do
        case "$1" in
            -c | --colors )
                shift
                COLORS="$1"
                ;;
            -i | --interval )
                shift
                INTERVAL="$1"
                ;;
            -m | --mem-width )
                shift
                MEM_WIDTH="$1"
                ;;
            -p | --cpu-width )
                shift
                CPU_WIDTH="$1"
                ;;
            -n | --num-iters )
                shift
                NUM_ITERS="$1"
                ;;
            * )
                usage
                exit 1
        esac
        shift
    done
}

get_os() {
    case "$OSTYPE" in
        linux*) echo linux ;;
        darwin*) echo macos ;;
        *) echo other ;;
    esac
}

# Based on $OS, output stats as "total_mem used_mem cpu_percent". Memory in MiB.
get_stats() {
    case "$OS" in
        linux) echo "$(get_stats_linux)" ;;
        macos) echo "$(get_stats_macos)" ;;
    esac
}

get_stats_linux() {
    local top_out="$(top -b -n 2 -d 1 -w 512)"

    local mem_row="$(echo "$top_out" | grep "MiB Mem" | tail -n 1)"
    local cpu_row="$(echo "$top_out" | grep "%Cpu(s)" | tail -n 1)"

    local total_mem="$(echo "$mem_row" | awk '{print $4}')"
    local used_mem="$(echo "$mem_row" | awk '{print $8}')"

    local cpu_user="$(echo "$cpu_row" | awk '{print $2}')"
    local cpu_sys="$(echo "$cpu_row" | awk '{print $4}')"

    local cpu_percent="$(echo "scale=1; $cpu_user + $cpu_sys" | bc)"

    echo "$total_mem $used_mem $cpu_percent"
}

get_stats_macos() {
    local top_out="$(top -l 2 -i 1 -n 0)"
    local vm_stat_out="$(vm_stat)"

    local page_size="$(echo "$vm_stat_out" | grep "page size of" | sed 's/[^0-9]//g')"
    local free="$(echo "$vm_stat_out" | grep "Pages free" | sed 's/[^0-9]//g')"
    local active="$(echo "$vm_stat_out" | grep "Pages active" | sed 's/[^0-9]//g')"
    local inactive="$(echo "$vm_stat_out" | grep "Pages inactive" | sed 's/[^0-9]//g')"
    local speculative="$(echo "$vm_stat_out" | grep "Pages speculative" | sed 's/[^0-9]//g')"
    local wired="$(echo "$vm_stat_out" | grep "Pages wired down" | sed 's/[^0-9]//g')"
    local compressed="$(echo "$vm_stat_out" | grep "Pages occupied by compressor" | sed 's/[^0-9]//g')"

    local total_mem=$(echo "scale=1;\
        ($free + $active + $inactive + $speculative + $wired + $compressed) *\
        $page_size / 1024 / 1024" | bc)

    local used_mem=$(echo "scale=1;\
        ($active + $wired) * $page_size / 1024 / 1024" | bc)

    local cpu_row="$(echo "$top_out" | grep "CPU usage" | tail -n 1)"

    local cpu_user="$(echo "$cpu_row" | awk '{print $3}' | sed 's/%//')"
    local cpu_sys="$(echo "$cpu_row" | awk '{print $5}' | sed 's/%//')"

    local cpu_percent="$(echo "scale=1; $cpu_user + $cpu_sys" | bc)"

    echo "$total_mem $used_mem $cpu_percent"
}

# Output a unicode bar representing $1 out of 100. The bar will be colorized
# according to $COLORS.
bar() {
    local b

    if [ "$(echo "$1 <= 18.75" | bc)" = "1" ] ; then
        b=▁
    elif [ "$(echo "$1 <= 31.25" | bc)" = "1" ] ; then
        b=▂
    elif [ "$(echo "$1 <= 43.75" | bc)" = "1" ] ; then
        b=▃
    elif [ "$(echo "$1 <= 56.25" | bc)" = "1" ] ; then
        b=▄
    elif [ "$(echo "$1 <= 68.75" | bc)" = "1" ] ; then
        b=▅
    elif [ "$(echo "$1 <= 81.25" | bc)" = "1" ] ; then
        b=▆
    elif [ "$(echo "$1 <= 93.75" | bc)" = "1" ] ; then
        b=▇
    else
        b=█
    fi

    if [ "$COLORS" = tmux ]; then
        echo "$(colorize_tmux $1 $b)"
    else
        echo "$b"
    fi
}

# Wrap $2 in tmux styles, with the color determined by $1 out of 100.
colorize_tmux() {
    local color

    if [ "$(echo "$1 <= 50" | bc)" = "1" ] ; then
        color=green
    elif [ "$(echo "$1 <= 75" | bc)" = "1" ] ; then
        color=yellow
    else
        color=red
    fi

    echo "#[fg=$color,bold]$2#[fg=default,default]"
}

main $@

