#!/bin/bash
#
# mem-cpu-stats - Print a summary of memory and CPU usage at a regular interval.
# Author: Jason Cox
# Repo: https://github.com/jasonccox/mem-cpu-stats

MEM_WIDTH=3
CPU_WIDTH=4
INTERVAL=5
NUM_ITERS=1
COLORS=

usage() {
    echo \
"USAGE: mem-cpu-stats [OPTIONS]

Available OPTIONS:
    -c | --colors STYLE        Colorize the bars in STYLE. Currently the only
                               supported style is tmux. Default none.
    -i | --interval INTERVAL   Print output every INTERVAL seconds. INTERVAL
                               must be an integer greater than 0. Default 5.
    -m | --mem-width WIDTH     Display the memory usage number with at least
                               WIDTH characters. Default 3.
    -n | --num-iters NUM       Exit after NUM intervals. An empty value is
                               interpreted as infinity. Default 1.
    -p | --cpu-width WIDTH     Display the CPU usage number with at least WIDTH
                               characters. Default 4.
"
}

main() {
    OS="$(get_os)"
    if [ "$OS" = other ]; then
        echo "unsupported OS"
        exit 1
    fi

    parse_options "$@"

    local n=0
    while true; do
        local stats=($(get_stats))

        local total_mem="${stats[0]}"
        local used_mem="${stats[1]}"
        local cpu_percent="${stats[2]}"

        local used_mem_gb="$(bc <<< "scale=1; $used_mem / 1024")"
        local mem_percent="$(bc <<< "scale=1; $used_mem * 100 / $total_mem")"

        local used_mem_fmt="$(printf '%*.1f' $MEM_WIDTH $used_mem_gb)"
        local cpu_percent_fmt="$(printf '%*.1f' $CPU_WIDTH $cpu_percent)"

        local mem_out="${used_mem_fmt}G $(bar $mem_percent)"
        local cpu_out="${cpu_percent_fmt}% $(bar $cpu_percent)"

        echo "$mem_out  $cpu_out"

        n="$((n + 1))"

        if [ -n "$NUM_ITERS" ] && [ "$n" -ge "$NUM_ITERS" ]; then
            break
        fi

        sleep $(($INTERVAL - 1)) # subtract 1 because top takes 1 second
    done
}

parse_options() {
    while [ "$1" != "" ]; do
        case "$1" in
            -c | --colors )
                shift
                COLORS="$1"
                ;;
            -i | --interval )
                shift
                INTERVAL="$1"
                ;;
            -m | --mem-width )
                shift
                MEM_WIDTH="$1"
                ;;
            -p | --cpu-width )
                shift
                CPU_WIDTH="$1"
                ;;
            -n | --num-iters )
                shift
                NUM_ITERS="$1"
                ;;
            * )
                usage
                exit 1
        esac
        shift
    done
}

get_os() {
    case "$OSTYPE" in
        linux*) echo linux ;;
        darwin*) echo macos ;;
        *) echo other ;;
    esac
}

# Based on $OS, output stats as "total_mem used_mem cpu_percent". Memory in MiB.
get_stats() {
    case "$OS" in
        linux) echo "$(get_stats_linux)" ;;
        macos) echo "$(get_stats_macos)" ;;
    esac
}

get_stats_linux() {
    local top_out="$(top -b -n 2 -d 1 -w 512)"

    local mem_row=($(grep "MiB Mem" <<< "$top_out" | tail -n 1))
    local cpu_row=($(grep "%Cpu(s)" <<< "$top_out" | tail -n 1))

    local total_mem="${mem_row[3]}"
    local used_mem="${mem_row[7]}"

    local cpu_user="${cpu_row[1]}"
    local cpu_sys="${cpu_row[3]}"

    local cpu_percent="$(bc <<< "scale=1; $cpu_user + $cpu_sys")"

    echo "$total_mem $used_mem $cpu_percent"
}

get_stats_macos() {
    local top_out="$(top -l 2 -i 1 -n 0)"
    local vm_stat_out="$(vm_stat)"

    local page_size="$(grep "page size of" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local free="$(grep "Pages free" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local active="$(grep "Pages active" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local inactive="$(grep "Pages inactive" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local speculative="$(grep "Pages speculative" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local wired="$(grep "Pages wired down" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"
    local compressed="$(grep "Pages occupied by compressor" <<< "$vm_stat_out" | sed 's/[^0-9]//g')"

    local total_mem=$(bc <<< "scale=1;\
        ($free + $active + $inactive + $speculative + $wired + $compressed) *\
        $page_size / 1024 / 1024")

    local used_mem=$(bc <<< "scale=1;\
        ($active + $wired) * $page_size / 1024 / 1024")

    local cpu_row=($(grep "CPU usage" <<< "$top_out" | tail -n 1))

    local cpu_user="${cpu_row[2]%\%}"
    local cpu_sys="${cpu_row[4]%\%}"

    local cpu_percent="$(bc <<< "scale=1; $cpu_user + $cpu_sys")"

    echo "$total_mem $used_mem $cpu_percent"
}

# Output a unicode bar representing $1 out of 100. The bar will be colorized
# according to $COLORS.
bar() {
    local b

    if [ "$(bc <<< "$1 <= 18.75")" = "1" ] ; then
        b=▁
    elif [ "$(bc <<< "$1 <= 31.25")" = "1" ] ; then
        b=▂
    elif [ "$(bc <<< "$1 <= 43.75")" = "1" ] ; then
        b=▃
    elif [ "$(bc <<< "$1 <= 56.25")" = "1" ] ; then
        b=▄
    elif [ "$(bc <<< "$1 <= 68.75")" = "1" ] ; then
        b=▅
    elif [ "$(bc <<< "$1 <= 81.25")" = "1" ] ; then
        b=▆
    elif [ "$(bc <<< "$1 <= 93.75")" = "1" ] ; then
        b=▇
    else
        b=█
    fi

    if [ "$COLORS" = tmux ]; then
        echo "$(colorize_tmux $1 $b)"
    else
        echo "$b"
    fi
}

# Wrap $2 in tmux styles, with the color determined by $1 out of 100.
colorize_tmux() {
    local color

    if [ "$(bc <<< "$1 <= 50")" = "1" ] ; then
        color=green
    elif [ "$(bc <<< "$1 <= 75")" = "1" ] ; then
        color=yellow
    else
        color=red
    fi

    echo "#[fg=$color,bold]$2#[fg=default,default]"
}

main "$@"

